#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.4f1_1f1dac67805b"
#define UNITY_VERSION_FULL_NICE "2019.4.4f1 (1f1dac67805b)"
#define UNITY_VERSION_BLD 2039212
#define UNITY_VERSION_DATE 1594177821
#define UNITY_VERSION_WIN "2019.4.4.2039212"
#define UNITY_VERSION_BRANCH "2019.4/staging"
